version: '3.9'
services:

  apache:
    build: './apache/'
    #restart: always
    container_name: apache
    ports:
      - 80:8000
      - 443:443
    volumes:
      - ./volumes/www/:/var/www/html
    networks:
      - frontend
      - backend

  php:
    build: './php/'
    #restart: always
    container_name: php
    expose:
      - 9000
    volumes:
      - ./volumes/www/:/var/www/html
    networks:
      - backend

  mysql:
    build: './mysql/'
    restart: always
    container_name: mysql
    expose:
      - 3306    
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306   
    volumes:
      - /volumes/mysql/:/var/lib/mysql/ 
    networks:
      - backend
      
networks:
  frontend:
  backend: