version: '3.9'
services:

  wdsn-apache2-php:
    build: './apache2-php/'
    restart: unless-stopped
    container_name: wdsn-apache2-php
    ports:
      - 80:8000
      - 443:443
    volumes:
      - ./volumes/www/:/var/www/html
      - ./volumes/apache2/sites-available/:/etc/apache2/sites-available
      - ./volumes/apache2/sites-enabled/:/etc/apache2/sites-enabled
    networks:
      - wdsn_network

  wdsn-mysql:
    build: './mysql/'
    restart: unless-stopped
    container_name: wdsn-mysql
    expose:
      - 3306    
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306   
    volumes:
      - ./volumes/mysql/:/var/lib/mysql/ 
    networks:
      - wdsn_network

  wdsn-phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: wdsn-phpmyadmin    
    links: 
      - wdsn-mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: wdsn-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1    
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wdsn_network  
      
networks:
  wdsn_network:
