# Download base image alpine 3.19
FROM httpd:alpine3.19

# About the custom image
LABEL maintainer="bsm.courrier@gmail.com"
LABEL version="1.0"
LABEL description="Docker Image for php8.1"

# Create "app" group
RUN addgroup -g 1000 app

# Create "app" user and join to group "app"
RUN adduser -D -H -h /var/www -s /sbin/nologin -G app -u 1000 app

# Create directory "/var/www/html"
RUN mkdir -p /var/www/html

# Set file user & group "app:app" as owner of directory's "/var/www" & "/usr/local/apache2/logs"
RUN chown -R app:app /var/www /usr/local/apache2/logs

# Listens on the specified network port
#EXPOSE 80 443

# specify the user name and group for CMD
USER app:app

# Sets the working directory for CMD
WORKDIR /var/www/html

# Execute httpd
CMD /usr/local/apache2/bin/httpd -D FOREGROUND
